- name: Configurar Database
  hosts: db_servers
  become: yes
  tasks:
    - name: Instalar Postgres
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: Criar Banco de Dados da Aplicação
      community.postgresql.postgresql_db:
        name: meu_banco_prod
        
    - name: Criar Usuário do Banco
      community.postgresql.postgresql_user:
        name: meu_usuario
        password: minha_senha_secreta