- name: Setup Database
  hosts: postgres_all
  become: true
  vars:
    pg_version: "17"
    db_name: "app_db"
    db_user: "app_user"

  tasks:
    - name: Install Postgres
      ansible.builtin.apt:
        name:
          - postgresql-{{ pg_version }}
          - postgresql-client-{{ pg_version }}
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: Set remote access
      ansible.builtin.lineinfile:
        path: /etc/postgresql/{{ pg_version }}/main/postgresql.conf
        regexp: "^listen_addresses"
        line: "listen_addresses = '*'"
      notify: Restart Postgres

    - name: Set wal level
      ansible.builtin.lineinfile:
        path: /etc/postgresql/{{ pg_version }}/main/postgresql.conf
        regexp: "^wal_level"
        line: "wal_level = replica"
      notify: Restart Postgres

    - name: Configure pg_hba.conf to allow postgres user from local subnet
      community.postgresql.postgresql_pg_hba:
        dest: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
        contype: host
        users: postgres
        databases: postgres
        method: scram-sha-256
        source: "192.168.1.0/24"
        state: present
      notify: Restart Postgres

  handlers:
    - name: Restart Postgres
      ansible.builtin.service:
        name: postgresql
        state: restarted
