- import_playbook: install_postgres.yml
  vars:
    target_hosts: postgres_all

- import_playbook: configure_primary.yml
  vars:
    target_hosts: primary

- import_playbook: configure_replicas.yml
  vars:
    target_hosts: replicas
